name: calculation
on: 
  push: 
    branches: 
      - 'main'
jobs:
  first-job:
    runs-on: windows-latest
    name: Save output
    steps:
    - shell: bash
      run: |
        expr 1 + 1 > output.txt
        name: Upload output file
        uses: actions/upload-artifact@v3
        with: 
          name: output-log-file
          path: output.txt
          

