name: calculation
on: 
  push: 
    branches: 
      - 'main'
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - uses: action/checkout@v3
      - name: calculate 1 + 1
      - shell: bash
        run: expr 1 + 1 > Result.txt
      - name: store results
      - uses: actions/upload-artifact@v3.1.0
        with: 
          name: result-log-file
          path: Result.txt
          

